Repository go-vela/vela-terraform, pull requests merged in 2020-05, with the labels that each got.

#4 feat: add ability to execute apply command
  cmd/vela-terraform/apply.go
  cmd/vela-terraform/apply_test.go
  cmd/vela-terraform/command.go
  cmd/vela-terraform/command_test.go
  cmd/vela-terraform/plan.go
  cmd/vela-terraform/terraform.go
  go.mod
  go.sum
Labels: feature

#6 enhancement(action): add the ability to run validate actions
  cmd/vela-terraform/apply.go
  cmd/vela-terraform/apply_test.go
  cmd/vela-terraform/validate.go
  cmd/vela-terraform/validate_test.go
Labels: enhancement

#8 feat(action): add terraform destroy command
  cmd/vela-terraform/destroy.go
  cmd/vela-terraform/destroy_test.go
Labels: feature

#7 feat(action): add terraform plan command
  cmd/vela-terraform/apply.go
  cmd/vela-terraform/plan.go
  cmd/vela-terraform/plan_test.go
  cmd/vela-terraform/validate.go
Labels: feature

#10 fix(apply): update var-file to be of type string array
  cmd/vela-terraform/apply.go
  cmd/vela-terraform/apply_test.go
Labels: bug

#9 feat(action): add terraform fmt command
  cmd/vela-terraform/destroy.go
  cmd/vela-terraform/fmt.go
  cmd/vela-terraform/fmt_test.go
Labels: feature

#11 enhancement: fill in validation and netrc funcs
  cmd/vela-terraform/config.go
  cmd/vela-terraform/config_test.go
  cmd/vela-terraform/old.go
  go.mod
  go.sum
Labels: enhancement

#12 docs: divert bugs and features to community
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement
